server = "{{ registry.server }}"

[host."{{ registry.url_normalized }}"]
  capabilities = ["pull", "resolve"]
  {%- if registry.ca %}
  ca = "{{ registry.ca }}"
  {%- endif %}
  {%- if registry.cert and registry.key %}
  client = [["{{ registry.cert }}", "{{ registry.key }}"]]
  {%- elif registry.cert %}
  client = "{{ registry.cert }}"
  {%- endif %}
  {%- if registry.insecure_skip_verify %}
  skip_verify = true
  {%- endif %}
